$axure.loadCurrentPage({
  "url":"001.html",
  "generationDate":new Date(1476581091182.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c3d88c2e1a49488cb26191a26bb06620",
    "type":"Axure:Page",
    "name":"001",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a3937de182b447497c349a02cc409a9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":60},
            "size":{
              "width":548,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618ad327994e44ca8a9bff2dd644d995",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c229d7d915934debb8d32f26036a3f81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"94b4229767c349bd87df192e90843e2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":294,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"882c154beaf141ea87250fa194297b8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u11.png"}},
{
              "id":"d697ce2bf0a248e6877bd1796c68b705",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":294,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57cdd2df8d824432829016ad58b9e043",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":294,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u3.png"}},
{
              "id":"a8cb99d72ddf49e29935efd96136cdf5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":254,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a4844eb292742ec9827124bbb668127",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":254,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u5.png"}},
{
              "id":"0a7db1961ca34843960bb1459936ca75",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":36},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45db8f113f024f9d98ec4f1dccce0cc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":36},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"784ac80d055347c1929570948d154488",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":66},
                "size":{
                  "width":254,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a49b2964a8e94cf5bf67ccd0ffd28d47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":66},
                    "size":{
                      "width":254,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u13.png"}},
{
              "id":"d4d2ee9b6671498b8d9941454156922f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fdace067ea54940a3c717fd784e8399",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"6e5e809b2937476d8f452491b52f6413",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":92},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58f32e517dd44910a0c63fe8798c75a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":92},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"1f1e73364c09440490b1e283a156925f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ee307f4882e42bfbfd9943f5cdaef7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"524f31f4d25f460d8d3dc72ff669a90b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":122},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33b38583d3cb44769cf0caa89f84500e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":122},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"4a1f52388cb843dc86e2e4dea24d2ce1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":152},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5e6516f393c4a6eb768b632cfd67ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":152},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u23.png"}},
{
              "id":"c159bd5f547b4d37976f4d3780ab45fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":152},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d619f282a9de4d7eabfc776eb60c398a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":152},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u25.png"}}]},
{
          "id":"8009b2b3be724c548f0b80b6e7b0ac5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":15},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 煤炭洗选中心电气维修部",
                      "target":{
                        "targetType":"page",
                        "url":"煤炭洗选中心电气维修部.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"af0e92fe10f943a7b230b05747142567",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":466.5,
              "y":870},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备保养情况查询",
                      "target":{
                        "targetType":"page",
                        "url":"设备保养情况查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0728928d53434be0aab0be929bc739e3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":201.5,
              "y":260},
            "size":{
              "width":629,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc2a087e13749ff998580ff3ab42cf7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":0},
                "size":{
                  "width":334,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc02a51c13924fc9b49f209d4c019d7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":0},
                    "size":{
                      "width":334,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u30.png"}},
{
              "id":"814886f8da504d9a9a90b7e62c671fa1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":36},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7996e2f4ce0146fb8a2086a424cfb872",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":36},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"3057c5c97ac543e39273e1895ed6e3ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff9e06070363420fad28f79c9b34c217",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u32.png"}},
{
              "id":"fead43ed00644b4093dc192fc320bddf",
              "label":"q1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":36},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"404598ae63dc425193752e45259da20c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":36},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"86e25bc2b23143e987e5fa52d2b48f4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":187,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb873d698da44109bd242e4d3a001504",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":187,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u34.png"}},
{
              "id":"311c9626089a45e5a06f52bbf3580a6e",
              "label":"w1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":36},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1079fe4ebb5a479a941a21f94739cec9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":36},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"36d04834a69a493bb96b31e383072561",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":38,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc8703814ee145bbba25f215b7e195e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":38,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u28.png"}},
{
              "id":"41cb31922bcd4d25bd655511d715e260",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9cc7712fb704cc4bc5e42eeaecc7f17",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"09c7d12b242249509aff1d25ced9f10d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":38,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"302b039f8fd145deada780ab328986be",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":38,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u44.png"}},
{
              "id":"6c3349f4d26e40d9b9f5c24f6104ac17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":77},
                "size":{
                  "width":334,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c7ae9c3a01144a1af73729d0b7e1c6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":77},
                    "size":{
                      "width":334,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u46.png"}},
{
              "id":"50d0806f1ab4432eb5b3031c1c8479d9",
              "label":"q2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":77},
                "size":{
                  "width":70,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c75f65a82bc34669a4e0c18ae5e5bd3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":77},
                    "size":{
                      "width":70,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q2_u48.png"}},
{
              "id":"eec738a9063f439d83edd9bf1ba3e209",
              "label":"w2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":77},
                "size":{
                  "width":187,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b5f476adae34edb80e46369a241bb58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":77},
                    "size":{
                      "width":187,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w2_u50.png"}},
{
              "id":"4e4a1335ce684068896dc91dd2df56ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4be7a9a0bb2e4484a65ec23789cd36c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"9993b7b48c9345e2941e2b2df4cdd78a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":122},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3adfb65d775042f18fb892be41341fff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":122},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"4a4b942bbceb4173a835a749893ee407",
              "label":"q3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":122},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"475eb82456294f55a7d697c701504313",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":122},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"9cb1ed585b514b939b74ebab708531cc",
              "label":"w3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":122},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cee52d9babf641a2b378d532e01c8f77",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":122},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"13d826ea40154a3686d22167121131b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":161},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb13e0f81009433cadbe5a5a242220e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":161},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"ea4a3c3b40c44a4781e0fc9e348679cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":161},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7be12199a7d9476c81c7a1f190c65c83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":161},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"cf396475fd37419a956fb0de6ec5d757",
              "label":"q4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":161},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"207654ea2fc64f37975d748b684442ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":161},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"a95da6f5551e4505a1d3990e5cfccc88",
              "label":"w4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":161},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11a83eca40d042c1bd36dcc824bb23ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":161},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"b733953d099346b089e320493324f461",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":201},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3483321297456d899d6b35217cef46",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":201},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"ee40222a7d8a43068d5d809e1ba6f111",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":201},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc745ce7da9d493ca909c5d306deb037",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":201},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"6f96567a3100425da60e21871a240a02",
              "label":"q5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":201},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98cc18237b13462ebb22cf9033337ede",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":201},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"f62de3562c20453dbcd2af0743f2e111",
              "label":"w5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":201},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4862540547c649008abd385add14ff05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":201},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"65cc2b0e3e1e4427957e05914afdb1c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":242},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4dd083f12344803bbe1312ae1747dff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"5d5d2540c5754025bfcbd73864125813",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":242},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46f22feacf244b3c8c7eb7e279bb6498",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":242},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"054bede2d6e44070904b2dc4805ed0e8",
              "label":"q6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":242},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"632de557da51464490dbcc20e4b23b49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":242},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"fba7e5e5546342c1ac161f7fb56b9dbf",
              "label":"w6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":242},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"026d3de9af014e0aa2bd8e0d0c31773e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":242},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"7190d61c46bb4d60b1dc6d88ee4cb161",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":283},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bef9587d851e47299ea681bd3852e5af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"09528ed696f04246bec7b15e04202a61",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":283},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78739f6a4f544615a8eb99fb6c7f3f25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":283},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"180726194c5e48e387935c0dbb7ef94f",
              "label":"q7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":283},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"53b60a2100bb4217a4ac8a2084427ece",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":283},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"6d8db787832440f4b7bee128d611c9fc",
              "label":"w7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":283},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5992347ee8474b0695d33405891fa6b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":283},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"d5375c21999f49618b6702bac95c448a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":323},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd9109759ccb41cbbba19543b5bae53a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":323},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"7713f62a8d794a1997cf7c46a2445753",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":323},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ee78efbe1ac43718e64d84d3501de39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":323},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"624db28bee6a4607b10ae67640208825",
              "label":"q8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":323},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0381a85aa574b72ab8f1cec6429262b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":323},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"b6092659f8614c40ab5f44889dbde17b",
              "label":"w8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":323},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51995a690f1645859adf3de56241c52e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":323},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"dfa469e5fbc148abab6f9013fe1a1653",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":366},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b912ce062d2040c7aed74394d7d3d362",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":366},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"4b27108f12db417283903e9f4a8ae9c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":366},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b636b562a344fcd99b42727ce369d7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":366},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"6947b0450bf64989b00e4de6f9bf6303",
              "label":"q9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":366},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6de37b368b5b4e23bcc74bf2ff1c9ca9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":366},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"7994560168224d0fb57e1dbc101b23d8",
              "label":"w9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":366},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed72ec5697f541599b225c960cf02960",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":366},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"6a3a024842174cd5bc6064378f570c96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":405},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08954ef9d45c4b5c8885993a3782dc7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":405},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"cc91f30d3d55475dbd5639e398ca39ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":405},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3126abb01e064ee18060b7da0fff6094",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":405},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"98a211a11e6e443caf8b42a2605b69e7",
              "label":"q10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":405},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9964fbe435bc4d3fa370d9083ce8d226",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":405},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"0f738b8dc7e443799b95f40a5ba276b0",
              "label":"w10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":405},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7eb4ee7a8f94ff2b450b636b9766cb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":405},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"2110b15a86434dff8a88dd1f9076ece9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":448},
                "size":{
                  "width":38,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7effd4b371b744ffbc9b55f85c280866",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":448},
                    "size":{
                      "width":38,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u116.png"}},
{
              "id":"c81eade289ff42998322c842614593ce",
              "label":"q11",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":448},
                "size":{
                  "width":334,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eaba29aeaa8e4afaadf1ada9a50d0380",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":448},
                    "size":{
                      "width":334,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q11_u118.png"}},
{
              "id":"b7395678b29b4ff887565f98c0b9ea78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":448},
                "size":{
                  "width":70,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"612182b053d34c928bcbe53dba46d995",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":448},
                    "size":{
                      "width":70,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u120.png"}},
{
              "id":"a6e69725caf741df9b846dac6773aa55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":448},
                "size":{
                  "width":187,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4bc1a06cbb8945d8bc5f866bcb461ac5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":448},
                    "size":{
                      "width":187,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u122.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "3a3937de182b447497c349a02cc409a9":{
      "scriptId":"u0"},
    "d697ce2bf0a248e6877bd1796c68b705":{
      "scriptId":"u1"},
    "57cdd2df8d824432829016ad58b9e043":{
      "scriptId":"u2"},
    "a8cb99d72ddf49e29935efd96136cdf5":{
      "scriptId":"u3"},
    "3a4844eb292742ec9827124bbb668127":{
      "scriptId":"u4"},
    "618ad327994e44ca8a9bff2dd644d995":{
      "scriptId":"u5"},
    "c229d7d915934debb8d32f26036a3f81":{
      "scriptId":"u6"},
    "0a7db1961ca34843960bb1459936ca75":{
      "scriptId":"u7"},
    "45db8f113f024f9d98ec4f1dccce0cc9":{
      "scriptId":"u8"},
    "94b4229767c349bd87df192e90843e2a":{
      "scriptId":"u9"},
    "882c154beaf141ea87250fa194297b8c":{
      "scriptId":"u10"},
    "784ac80d055347c1929570948d154488":{
      "scriptId":"u11"},
    "a49b2964a8e94cf5bf67ccd0ffd28d47":{
      "scriptId":"u12"},
    "d4d2ee9b6671498b8d9941454156922f":{
      "scriptId":"u13"},
    "7fdace067ea54940a3c717fd784e8399":{
      "scriptId":"u14"},
    "6e5e809b2937476d8f452491b52f6413":{
      "scriptId":"u15"},
    "58f32e517dd44910a0c63fe8798c75a0":{
      "scriptId":"u16"},
    "1f1e73364c09440490b1e283a156925f":{
      "scriptId":"u17"},
    "8ee307f4882e42bfbfd9943f5cdaef7b":{
      "scriptId":"u18"},
    "524f31f4d25f460d8d3dc72ff669a90b":{
      "scriptId":"u19"},
    "33b38583d3cb44769cf0caa89f84500e":{
      "scriptId":"u20"},
    "4a1f52388cb843dc86e2e4dea24d2ce1":{
      "scriptId":"u21"},
    "d5e6516f393c4a6eb768b632cfd67ecc":{
      "scriptId":"u22"},
    "c159bd5f547b4d37976f4d3780ab45fc":{
      "scriptId":"u23"},
    "d619f282a9de4d7eabfc776eb60c398a":{
      "scriptId":"u24"},
    "8009b2b3be724c548f0b80b6e7b0ac5d":{
      "scriptId":"u25"},
    "af0e92fe10f943a7b230b05747142567":{
      "scriptId":"u26"},
    "0728928d53434be0aab0be929bc739e3":{
      "scriptId":"u27"},
    "36d04834a69a493bb96b31e383072561":{
      "scriptId":"u28"},
    "fc8703814ee145bbba25f215b7e195e7":{
      "scriptId":"u29"},
    "0dc2a087e13749ff998580ff3ab42cf7":{
      "scriptId":"u30"},
    "fc02a51c13924fc9b49f209d4c019d7b":{
      "scriptId":"u31"},
    "3057c5c97ac543e39273e1895ed6e3ae":{
      "scriptId":"u32"},
    "ff9e06070363420fad28f79c9b34c217":{
      "scriptId":"u33"},
    "86e25bc2b23143e987e5fa52d2b48f4d":{
      "scriptId":"u34"},
    "eb873d698da44109bd242e4d3a001504":{
      "scriptId":"u35"},
    "41cb31922bcd4d25bd655511d715e260":{
      "scriptId":"u36"},
    "c9cc7712fb704cc4bc5e42eeaecc7f17":{
      "scriptId":"u37"},
    "814886f8da504d9a9a90b7e62c671fa1":{
      "scriptId":"u38"},
    "7996e2f4ce0146fb8a2086a424cfb872":{
      "scriptId":"u39"},
    "fead43ed00644b4093dc192fc320bddf":{
      "scriptId":"u40"},
    "404598ae63dc425193752e45259da20c":{
      "scriptId":"u41"},
    "311c9626089a45e5a06f52bbf3580a6e":{
      "scriptId":"u42"},
    "1079fe4ebb5a479a941a21f94739cec9":{
      "scriptId":"u43"},
    "09c7d12b242249509aff1d25ced9f10d":{
      "scriptId":"u44"},
    "302b039f8fd145deada780ab328986be":{
      "scriptId":"u45"},
    "6c3349f4d26e40d9b9f5c24f6104ac17":{
      "scriptId":"u46"},
    "8c7ae9c3a01144a1af73729d0b7e1c6a":{
      "scriptId":"u47"},
    "50d0806f1ab4432eb5b3031c1c8479d9":{
      "scriptId":"u48"},
    "c75f65a82bc34669a4e0c18ae5e5bd3e":{
      "scriptId":"u49"},
    "eec738a9063f439d83edd9bf1ba3e209":{
      "scriptId":"u50"},
    "3b5f476adae34edb80e46369a241bb58":{
      "scriptId":"u51"},
    "4e4a1335ce684068896dc91dd2df56ff":{
      "scriptId":"u52"},
    "4be7a9a0bb2e4484a65ec23789cd36c2":{
      "scriptId":"u53"},
    "9993b7b48c9345e2941e2b2df4cdd78a":{
      "scriptId":"u54"},
    "3adfb65d775042f18fb892be41341fff":{
      "scriptId":"u55"},
    "4a4b942bbceb4173a835a749893ee407":{
      "scriptId":"u56"},
    "475eb82456294f55a7d697c701504313":{
      "scriptId":"u57"},
    "9cb1ed585b514b939b74ebab708531cc":{
      "scriptId":"u58"},
    "cee52d9babf641a2b378d532e01c8f77":{
      "scriptId":"u59"},
    "13d826ea40154a3686d22167121131b5":{
      "scriptId":"u60"},
    "fb13e0f81009433cadbe5a5a242220e2":{
      "scriptId":"u61"},
    "ea4a3c3b40c44a4781e0fc9e348679cd":{
      "scriptId":"u62"},
    "7be12199a7d9476c81c7a1f190c65c83":{
      "scriptId":"u63"},
    "cf396475fd37419a956fb0de6ec5d757":{
      "scriptId":"u64"},
    "207654ea2fc64f37975d748b684442ee":{
      "scriptId":"u65"},
    "a95da6f5551e4505a1d3990e5cfccc88":{
      "scriptId":"u66"},
    "11a83eca40d042c1bd36dcc824bb23ae":{
      "scriptId":"u67"},
    "b733953d099346b089e320493324f461":{
      "scriptId":"u68"},
    "df3483321297456d899d6b35217cef46":{
      "scriptId":"u69"},
    "ee40222a7d8a43068d5d809e1ba6f111":{
      "scriptId":"u70"},
    "cc745ce7da9d493ca909c5d306deb037":{
      "scriptId":"u71"},
    "6f96567a3100425da60e21871a240a02":{
      "scriptId":"u72"},
    "98cc18237b13462ebb22cf9033337ede":{
      "scriptId":"u73"},
    "f62de3562c20453dbcd2af0743f2e111":{
      "scriptId":"u74"},
    "4862540547c649008abd385add14ff05":{
      "scriptId":"u75"},
    "65cc2b0e3e1e4427957e05914afdb1c7":{
      "scriptId":"u76"},
    "d4dd083f12344803bbe1312ae1747dff":{
      "scriptId":"u77"},
    "5d5d2540c5754025bfcbd73864125813":{
      "scriptId":"u78"},
    "46f22feacf244b3c8c7eb7e279bb6498":{
      "scriptId":"u79"},
    "054bede2d6e44070904b2dc4805ed0e8":{
      "scriptId":"u80"},
    "632de557da51464490dbcc20e4b23b49":{
      "scriptId":"u81"},
    "fba7e5e5546342c1ac161f7fb56b9dbf":{
      "scriptId":"u82"},
    "026d3de9af014e0aa2bd8e0d0c31773e":{
      "scriptId":"u83"},
    "7190d61c46bb4d60b1dc6d88ee4cb161":{
      "scriptId":"u84"},
    "bef9587d851e47299ea681bd3852e5af":{
      "scriptId":"u85"},
    "09528ed696f04246bec7b15e04202a61":{
      "scriptId":"u86"},
    "78739f6a4f544615a8eb99fb6c7f3f25":{
      "scriptId":"u87"},
    "180726194c5e48e387935c0dbb7ef94f":{
      "scriptId":"u88"},
    "53b60a2100bb4217a4ac8a2084427ece":{
      "scriptId":"u89"},
    "6d8db787832440f4b7bee128d611c9fc":{
      "scriptId":"u90"},
    "5992347ee8474b0695d33405891fa6b7":{
      "scriptId":"u91"},
    "d5375c21999f49618b6702bac95c448a":{
      "scriptId":"u92"},
    "fd9109759ccb41cbbba19543b5bae53a":{
      "scriptId":"u93"},
    "7713f62a8d794a1997cf7c46a2445753":{
      "scriptId":"u94"},
    "5ee78efbe1ac43718e64d84d3501de39":{
      "scriptId":"u95"},
    "624db28bee6a4607b10ae67640208825":{
      "scriptId":"u96"},
    "a0381a85aa574b72ab8f1cec6429262b":{
      "scriptId":"u97"},
    "b6092659f8614c40ab5f44889dbde17b":{
      "scriptId":"u98"},
    "51995a690f1645859adf3de56241c52e":{
      "scriptId":"u99"},
    "dfa469e5fbc148abab6f9013fe1a1653":{
      "scriptId":"u100"},
    "b912ce062d2040c7aed74394d7d3d362":{
      "scriptId":"u101"},
    "4b27108f12db417283903e9f4a8ae9c2":{
      "scriptId":"u102"},
    "8b636b562a344fcd99b42727ce369d7f":{
      "scriptId":"u103"},
    "6947b0450bf64989b00e4de6f9bf6303":{
      "scriptId":"u104"},
    "6de37b368b5b4e23bcc74bf2ff1c9ca9":{
      "scriptId":"u105"},
    "7994560168224d0fb57e1dbc101b23d8":{
      "scriptId":"u106"},
    "ed72ec5697f541599b225c960cf02960":{
      "scriptId":"u107"},
    "6a3a024842174cd5bc6064378f570c96":{
      "scriptId":"u108"},
    "08954ef9d45c4b5c8885993a3782dc7e":{
      "scriptId":"u109"},
    "cc91f30d3d55475dbd5639e398ca39ba":{
      "scriptId":"u110"},
    "3126abb01e064ee18060b7da0fff6094":{
      "scriptId":"u111"},
    "98a211a11e6e443caf8b42a2605b69e7":{
      "scriptId":"u112"},
    "9964fbe435bc4d3fa370d9083ce8d226":{
      "scriptId":"u113"},
    "0f738b8dc7e443799b95f40a5ba276b0":{
      "scriptId":"u114"},
    "b7eb4ee7a8f94ff2b450b636b9766cb1":{
      "scriptId":"u115"},
    "2110b15a86434dff8a88dd1f9076ece9":{
      "scriptId":"u116"},
    "7effd4b371b744ffbc9b55f85c280866":{
      "scriptId":"u117"},
    "c81eade289ff42998322c842614593ce":{
      "scriptId":"u118"},
    "eaba29aeaa8e4afaadf1ada9a50d0380":{
      "scriptId":"u119"},
    "b7395678b29b4ff887565f98c0b9ea78":{
      "scriptId":"u120"},
    "612182b053d34c928bcbe53dba46d995":{
      "scriptId":"u121"},
    "a6e69725caf741df9b846dac6773aa55":{
      "scriptId":"u122"},
    "4bc1a06cbb8945d8bc5f866bcb461ac5":{
      "scriptId":"u123"}}});