$axure.loadCurrentPage({
  "url":"002.html",
  "generationDate":new Date(1476581092078.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"af22e60dc88a48c284bdcd80ab7e7869",
    "type":"Axure:Page",
    "name":"002",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c054f3d7ff0c42bd8a3f922c48be0d4f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":60},
            "size":{
              "width":548,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fb99a2e68a441387506ba4c1d15ca8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e500242525e5405e909b5c542f79a78c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"4996163a91a347048f0ef517070f7abb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":294,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2243fed0629d4eb1aa4654c6fc71e3e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u11.png"}},
{
              "id":"cb2b958cd8024c77a87185b1338c40e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":294,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57912dcb26a64d32bbe7b34a21abf56e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":294,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u3.png"}},
{
              "id":"e2e29a8b71074ee5b434ae156f15c51b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":254,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15bad60f315c420db918da03ad46d24f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":254,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u5.png"}},
{
              "id":"d07d66d7fdf04e709dda7ae21ac24f25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":36},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d26cda0b77249e4b2b9ec46c6ae7f55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":36},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"f5fb2cfb9e4b4c0d9b32b6fbe49b0f13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":66},
                "size":{
                  "width":254,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"977181abe07a48ff8d62ed7cb16fab7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":66},
                    "size":{
                      "width":254,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u13.png"}},
{
              "id":"fee3eca1a5634eba8b21f07caf7319ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c4c98b41c544402a8d139a58f036fde",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"f0cb664448fb40b5950d2f8537a7bc63",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":92},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ac3d7b9cdf6475789f3874cca896922",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":92},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"bfe38f9060b642c1af27edf5f511d30e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"348c7a8c48de46a883cec8c2e58334c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"811180e567c648ccaadb5372f7670c01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":122},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"289cd2953dbb46bfb329b12db595c014",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":122},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"0ab05e10f0374a0ea6c5310bc04522b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":152},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f84ef3df2fc4e5ebc37fef7a6990b32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":152},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u23.png"}},
{
              "id":"38adb5eb12fe46c29c3c828ad6147c19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":152},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ceff9a31f9704bf5804ac5855c7f50d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":152},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u25.png"}}]},
{
          "id":"7bb94c1e59da4f7990f228ef2a0a8291",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":201.5,
              "y":260},
            "size":{
              "width":629,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5947e984da44c39a595840b040b6123",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":0},
                "size":{
                  "width":334,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d01b5f4efd5472ea007a69c5ade168a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":0},
                    "size":{
                      "width":334,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u30.png"}},
{
              "id":"129f66d664e843528ab34a5adc5cc74b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":36},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e056234ae40e4bc597e2f9f4561fb39b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":36},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"66760d44cb7a490eb2237de100e919fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"072782dadedc4652bbc5ec25acc79dda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u32.png"}},
{
              "id":"41c09cd2830d40768f4e9e9a42fd69a5",
              "label":"q1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":36},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fca1770fe3da4661aec9ba552e85327e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":36},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"a8a805afe2184e22a64e48f567541bc4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":187,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4190faefaa64508af7642d41273d34e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":187,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u34.png"}},
{
              "id":"1ce9d0c7d2ab42329239374703abab6c",
              "label":"w1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":36},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"729630f6c6a34315906921f0eadeb26a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":36},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"7704a3e9dc1245b99f1e5e366dd4a105",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":38,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2a3ca1e6845428994af900258376ddc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":38,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u28.png"}},
{
              "id":"c10a5aaa15bf4e02b13bb871614ead6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9946acbd9f84fc4ab9a3d9af1b5540d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"43a46ea1d06446398d77d85fda0c0f32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":38,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f10e2b2e762c4799a78b185109d252af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":38,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u44.png"}},
{
              "id":"c564065e667346329b2dc7c115259fa0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":77},
                "size":{
                  "width":334,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2879c0602b2e49ff91a0fa646070ca67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":77},
                    "size":{
                      "width":334,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u46.png"}},
{
              "id":"730d8735501a4974bcdf827c0347bc8c",
              "label":"q2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":77},
                "size":{
                  "width":70,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"081158e4269d45f283615b86dc59dde9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":77},
                    "size":{
                      "width":70,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q2_u48.png"}},
{
              "id":"fb209b4c4dde43d4903c25953029d29d",
              "label":"w2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":77},
                "size":{
                  "width":187,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5326f3acfc1543b4bee23a3028ba34be",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":77},
                    "size":{
                      "width":187,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w2_u50.png"}},
{
              "id":"fe6dd7155bf9441cbd74428e5590c57a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"439d9fa2ba774a3cb02e2fb2943bc81c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"0d1669d11e9c48ff996288a3a12d0b3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":122},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e170c5d2a1f4b31ac67403ad02c0462",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":122},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"8bf9af6c30d64f428bf5f31b2ec7a029",
              "label":"q3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":122},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d87b5b86884460d8b04e8533b05635b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":122},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"b0d8a778097744feb04b3f8fd1d805cd",
              "label":"w3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":122},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b8069075d1044e495efd396cc3640b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":122},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"3369f86ab21043649ae0abaa7255faeb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":161},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9e635a724f54284a9474f5873fb053f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":161},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"5fa710eaa15f4d6588085f2cbc9743e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":161},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a00b8cf834f549d3b35c49fbe66e5231",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":161},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"236a32d22fc0430db9d2df81c903cea5",
              "label":"q4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":161},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8094df3d7e5143a1b34e887a1ed1cef4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":161},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"4186094eaad94e39b8df616593fe301b",
              "label":"w4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":161},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b23eb485d7a74eb6ad5b704a027e7fe3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":161},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"76befc1cd216439ba4aa6c5bef318e5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":201},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dffdc9ab73184894b598e9a141cb9e00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":201},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"f488bbec3e57481a9fcaf3b7d1fc686f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":201},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ee53851ec1d461ba193b02642138d99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":201},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"63ec85d47c974df5a9416df1aa43ea25",
              "label":"q5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":201},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c5e19284f404238ac2cb71f73fa09f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":201},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"d977f8c970f340a7906e79588c60e9e7",
              "label":"w5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":201},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"810ca9fa52ce49ad800720c8b3f04aab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":201},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"b26dbb5def5c4e149fbf0cf0954960a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":242},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"848432827ecb411aa412f25ca97838eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"8a5179a32ca149618e5a218dc9c6a367",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":242},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58fae58bb0cd46c2bb9b67c9064bff09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":242},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"f627da600ca84477945147ffac095a2b",
              "label":"q6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":242},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35df914422b2434b9bd64f041ddf65d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":242},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"a74a08f4d01e459e9c7f63780dab6870",
              "label":"w6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":242},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ee7d5b2183b4af6879ce69965b1dd01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":242},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"ea6ca3c229914226a0314c23b39aec99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":283},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"557b053a58ff46518c751ecb4a4418ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"e1eab3068bcc46e89a740211716763dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":283},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4dc7955aec59430faf3b0f66ea61a9cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":283},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"2712bc46bc91483298700ea281ed8895",
              "label":"q7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":283},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9427eafabb464a7581e78d9397cf1c38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":283},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"6bed880beb02474c8dcee37e9678d1c6",
              "label":"w7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":283},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eac812ee853d449ca3d14afaeb23a78a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":283},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"cb9c0be6416845ee9227fb545d8fef14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":323},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c478315b85e04b98bc376fe2fb856ed5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":323},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"b05b54051db34dab8a89c6f11431821f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":323},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3fe260963abb46ca8137b82db38a135c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":323},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"ba5c3d3f4b7144dab6b6f9e22e68d0f4",
              "label":"q8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":323},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85e1ed1deb76469297ae9d577a04e98d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":323},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"09059b6e198a46cea7250fd04e4cf5e8",
              "label":"w8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":323},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa90829e1df44aaa9ae8849e3313b748",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":323},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"c4e100778840401791e0f9b6405be889",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":366},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d012d0e9c00b40ab978989c3f8bf1f02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":366},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"1efcc1cf891c4f2d933c9cdf3a7c31e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":366},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61d766aa50d9458b939b58b899b285b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":366},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"af95717d26ff451cbcba78f9a018e948",
              "label":"q9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":366},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4455fc9012864ce79115c83dafdd049c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":366},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"29e985ab943149619c74f9b3db1c4d21",
              "label":"w9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":366},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0447fd7298145fb87c5f2e0d823a8e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":366},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"73a4580624a44c3c89b739ff269b0349",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":405},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"adfb6269b33d49729c0485816d4cb309",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":405},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"c8f45db71b994ad089cc044c7808d180",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":405},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28b92046f9f74785a2657267059fc16a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":405},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"9abe85b3224f4865a20deaf6a9230bfd",
              "label":"q10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":405},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91e86592e06542b48f9a3c39995dfd5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":405},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"0b517fc1eff44aa1bdcbf53e1a77729a",
              "label":"w10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":405},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8bba4be5f9549c38c0ecf2aef7f46ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":405},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"6e7eb5416c684c6aa9e02af2007dffb8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":448},
                "size":{
                  "width":38,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f47be9ed9c24bfab68a30166b99279d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":448},
                    "size":{
                      "width":38,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u116.png"}},
{
              "id":"a48d5592393346c7a7dbb8af1f1491a8",
              "label":"q11",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":448},
                "size":{
                  "width":334,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb51f6e85740430682106d37906b232e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":448},
                    "size":{
                      "width":334,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q11_u118.png"}},
{
              "id":"dab58631074741f9a6b3f8eb4503bc7a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":448},
                "size":{
                  "width":70,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17b81a2014db4878a50ed84ffdc1076a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":448},
                    "size":{
                      "width":70,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u120.png"}},
{
              "id":"dfc5fbe808e0466ba96c026408dc064a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":448},
                "size":{
                  "width":187,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56baf258497046109ef63d4e1dacc6ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":448},
                    "size":{
                      "width":187,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u122.png"}}]},
{
          "id":"b210267f9c07429b84ca8c2d07ebe915",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":35},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 煤炭洗选中心电气维修部",
                      "target":{
                        "targetType":"page",
                        "url":"煤炭洗选中心电气维修部.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"159fb0056727481eaae428256dac1db7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":870},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备保养情况查询",
                      "target":{
                        "targetType":"page",
                        "url":"设备保养情况查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "c054f3d7ff0c42bd8a3f922c48be0d4f":{
      "scriptId":"u0"},
    "cb2b958cd8024c77a87185b1338c40e1":{
      "scriptId":"u1"},
    "57912dcb26a64d32bbe7b34a21abf56e":{
      "scriptId":"u2"},
    "e2e29a8b71074ee5b434ae156f15c51b":{
      "scriptId":"u3"},
    "15bad60f315c420db918da03ad46d24f":{
      "scriptId":"u4"},
    "94fb99a2e68a441387506ba4c1d15ca8":{
      "scriptId":"u5"},
    "e500242525e5405e909b5c542f79a78c":{
      "scriptId":"u6"},
    "d07d66d7fdf04e709dda7ae21ac24f25":{
      "scriptId":"u7"},
    "1d26cda0b77249e4b2b9ec46c6ae7f55":{
      "scriptId":"u8"},
    "4996163a91a347048f0ef517070f7abb":{
      "scriptId":"u9"},
    "2243fed0629d4eb1aa4654c6fc71e3e8":{
      "scriptId":"u10"},
    "f5fb2cfb9e4b4c0d9b32b6fbe49b0f13":{
      "scriptId":"u11"},
    "977181abe07a48ff8d62ed7cb16fab7e":{
      "scriptId":"u12"},
    "fee3eca1a5634eba8b21f07caf7319ea":{
      "scriptId":"u13"},
    "9c4c98b41c544402a8d139a58f036fde":{
      "scriptId":"u14"},
    "f0cb664448fb40b5950d2f8537a7bc63":{
      "scriptId":"u15"},
    "2ac3d7b9cdf6475789f3874cca896922":{
      "scriptId":"u16"},
    "bfe38f9060b642c1af27edf5f511d30e":{
      "scriptId":"u17"},
    "348c7a8c48de46a883cec8c2e58334c1":{
      "scriptId":"u18"},
    "811180e567c648ccaadb5372f7670c01":{
      "scriptId":"u19"},
    "289cd2953dbb46bfb329b12db595c014":{
      "scriptId":"u20"},
    "0ab05e10f0374a0ea6c5310bc04522b2":{
      "scriptId":"u21"},
    "2f84ef3df2fc4e5ebc37fef7a6990b32":{
      "scriptId":"u22"},
    "38adb5eb12fe46c29c3c828ad6147c19":{
      "scriptId":"u23"},
    "ceff9a31f9704bf5804ac5855c7f50d3":{
      "scriptId":"u24"},
    "7bb94c1e59da4f7990f228ef2a0a8291":{
      "scriptId":"u25"},
    "7704a3e9dc1245b99f1e5e366dd4a105":{
      "scriptId":"u26"},
    "e2a3ca1e6845428994af900258376ddc":{
      "scriptId":"u27"},
    "d5947e984da44c39a595840b040b6123":{
      "scriptId":"u28"},
    "7d01b5f4efd5472ea007a69c5ade168a":{
      "scriptId":"u29"},
    "66760d44cb7a490eb2237de100e919fb":{
      "scriptId":"u30"},
    "072782dadedc4652bbc5ec25acc79dda":{
      "scriptId":"u31"},
    "a8a805afe2184e22a64e48f567541bc4":{
      "scriptId":"u32"},
    "b4190faefaa64508af7642d41273d34e":{
      "scriptId":"u33"},
    "c10a5aaa15bf4e02b13bb871614ead6e":{
      "scriptId":"u34"},
    "a9946acbd9f84fc4ab9a3d9af1b5540d":{
      "scriptId":"u35"},
    "129f66d664e843528ab34a5adc5cc74b":{
      "scriptId":"u36"},
    "e056234ae40e4bc597e2f9f4561fb39b":{
      "scriptId":"u37"},
    "41c09cd2830d40768f4e9e9a42fd69a5":{
      "scriptId":"u38"},
    "fca1770fe3da4661aec9ba552e85327e":{
      "scriptId":"u39"},
    "1ce9d0c7d2ab42329239374703abab6c":{
      "scriptId":"u40"},
    "729630f6c6a34315906921f0eadeb26a":{
      "scriptId":"u41"},
    "43a46ea1d06446398d77d85fda0c0f32":{
      "scriptId":"u42"},
    "f10e2b2e762c4799a78b185109d252af":{
      "scriptId":"u43"},
    "c564065e667346329b2dc7c115259fa0":{
      "scriptId":"u44"},
    "2879c0602b2e49ff91a0fa646070ca67":{
      "scriptId":"u45"},
    "730d8735501a4974bcdf827c0347bc8c":{
      "scriptId":"u46"},
    "081158e4269d45f283615b86dc59dde9":{
      "scriptId":"u47"},
    "fb209b4c4dde43d4903c25953029d29d":{
      "scriptId":"u48"},
    "5326f3acfc1543b4bee23a3028ba34be":{
      "scriptId":"u49"},
    "fe6dd7155bf9441cbd74428e5590c57a":{
      "scriptId":"u50"},
    "439d9fa2ba774a3cb02e2fb2943bc81c":{
      "scriptId":"u51"},
    "0d1669d11e9c48ff996288a3a12d0b3d":{
      "scriptId":"u52"},
    "4e170c5d2a1f4b31ac67403ad02c0462":{
      "scriptId":"u53"},
    "8bf9af6c30d64f428bf5f31b2ec7a029":{
      "scriptId":"u54"},
    "7d87b5b86884460d8b04e8533b05635b":{
      "scriptId":"u55"},
    "b0d8a778097744feb04b3f8fd1d805cd":{
      "scriptId":"u56"},
    "1b8069075d1044e495efd396cc3640b9":{
      "scriptId":"u57"},
    "3369f86ab21043649ae0abaa7255faeb":{
      "scriptId":"u58"},
    "b9e635a724f54284a9474f5873fb053f":{
      "scriptId":"u59"},
    "5fa710eaa15f4d6588085f2cbc9743e4":{
      "scriptId":"u60"},
    "a00b8cf834f549d3b35c49fbe66e5231":{
      "scriptId":"u61"},
    "236a32d22fc0430db9d2df81c903cea5":{
      "scriptId":"u62"},
    "8094df3d7e5143a1b34e887a1ed1cef4":{
      "scriptId":"u63"},
    "4186094eaad94e39b8df616593fe301b":{
      "scriptId":"u64"},
    "b23eb485d7a74eb6ad5b704a027e7fe3":{
      "scriptId":"u65"},
    "76befc1cd216439ba4aa6c5bef318e5b":{
      "scriptId":"u66"},
    "dffdc9ab73184894b598e9a141cb9e00":{
      "scriptId":"u67"},
    "f488bbec3e57481a9fcaf3b7d1fc686f":{
      "scriptId":"u68"},
    "1ee53851ec1d461ba193b02642138d99":{
      "scriptId":"u69"},
    "63ec85d47c974df5a9416df1aa43ea25":{
      "scriptId":"u70"},
    "0c5e19284f404238ac2cb71f73fa09f7":{
      "scriptId":"u71"},
    "d977f8c970f340a7906e79588c60e9e7":{
      "scriptId":"u72"},
    "810ca9fa52ce49ad800720c8b3f04aab":{
      "scriptId":"u73"},
    "b26dbb5def5c4e149fbf0cf0954960a2":{
      "scriptId":"u74"},
    "848432827ecb411aa412f25ca97838eb":{
      "scriptId":"u75"},
    "8a5179a32ca149618e5a218dc9c6a367":{
      "scriptId":"u76"},
    "58fae58bb0cd46c2bb9b67c9064bff09":{
      "scriptId":"u77"},
    "f627da600ca84477945147ffac095a2b":{
      "scriptId":"u78"},
    "35df914422b2434b9bd64f041ddf65d8":{
      "scriptId":"u79"},
    "a74a08f4d01e459e9c7f63780dab6870":{
      "scriptId":"u80"},
    "4ee7d5b2183b4af6879ce69965b1dd01":{
      "scriptId":"u81"},
    "ea6ca3c229914226a0314c23b39aec99":{
      "scriptId":"u82"},
    "557b053a58ff46518c751ecb4a4418ab":{
      "scriptId":"u83"},
    "e1eab3068bcc46e89a740211716763dd":{
      "scriptId":"u84"},
    "4dc7955aec59430faf3b0f66ea61a9cd":{
      "scriptId":"u85"},
    "2712bc46bc91483298700ea281ed8895":{
      "scriptId":"u86"},
    "9427eafabb464a7581e78d9397cf1c38":{
      "scriptId":"u87"},
    "6bed880beb02474c8dcee37e9678d1c6":{
      "scriptId":"u88"},
    "eac812ee853d449ca3d14afaeb23a78a":{
      "scriptId":"u89"},
    "cb9c0be6416845ee9227fb545d8fef14":{
      "scriptId":"u90"},
    "c478315b85e04b98bc376fe2fb856ed5":{
      "scriptId":"u91"},
    "b05b54051db34dab8a89c6f11431821f":{
      "scriptId":"u92"},
    "3fe260963abb46ca8137b82db38a135c":{
      "scriptId":"u93"},
    "ba5c3d3f4b7144dab6b6f9e22e68d0f4":{
      "scriptId":"u94"},
    "85e1ed1deb76469297ae9d577a04e98d":{
      "scriptId":"u95"},
    "09059b6e198a46cea7250fd04e4cf5e8":{
      "scriptId":"u96"},
    "fa90829e1df44aaa9ae8849e3313b748":{
      "scriptId":"u97"},
    "c4e100778840401791e0f9b6405be889":{
      "scriptId":"u98"},
    "d012d0e9c00b40ab978989c3f8bf1f02":{
      "scriptId":"u99"},
    "1efcc1cf891c4f2d933c9cdf3a7c31e1":{
      "scriptId":"u100"},
    "61d766aa50d9458b939b58b899b285b2":{
      "scriptId":"u101"},
    "af95717d26ff451cbcba78f9a018e948":{
      "scriptId":"u102"},
    "4455fc9012864ce79115c83dafdd049c":{
      "scriptId":"u103"},
    "29e985ab943149619c74f9b3db1c4d21":{
      "scriptId":"u104"},
    "e0447fd7298145fb87c5f2e0d823a8e8":{
      "scriptId":"u105"},
    "73a4580624a44c3c89b739ff269b0349":{
      "scriptId":"u106"},
    "adfb6269b33d49729c0485816d4cb309":{
      "scriptId":"u107"},
    "c8f45db71b994ad089cc044c7808d180":{
      "scriptId":"u108"},
    "28b92046f9f74785a2657267059fc16a":{
      "scriptId":"u109"},
    "9abe85b3224f4865a20deaf6a9230bfd":{
      "scriptId":"u110"},
    "91e86592e06542b48f9a3c39995dfd5f":{
      "scriptId":"u111"},
    "0b517fc1eff44aa1bdcbf53e1a77729a":{
      "scriptId":"u112"},
    "f8bba4be5f9549c38c0ecf2aef7f46ec":{
      "scriptId":"u113"},
    "6e7eb5416c684c6aa9e02af2007dffb8":{
      "scriptId":"u114"},
    "5f47be9ed9c24bfab68a30166b99279d":{
      "scriptId":"u115"},
    "a48d5592393346c7a7dbb8af1f1491a8":{
      "scriptId":"u116"},
    "bb51f6e85740430682106d37906b232e":{
      "scriptId":"u117"},
    "dab58631074741f9a6b3f8eb4503bc7a":{
      "scriptId":"u118"},
    "17b81a2014db4878a50ed84ffdc1076a":{
      "scriptId":"u119"},
    "dfc5fbe808e0466ba96c026408dc064a":{
      "scriptId":"u120"},
    "56baf258497046109ef63d4e1dacc6ee":{
      "scriptId":"u121"},
    "b210267f9c07429b84ca8c2d07ebe915":{
      "scriptId":"u122"},
    "159fb0056727481eaae428256dac1db7":{
      "scriptId":"u123"}}});