$axure.loadCurrentPage({
  "url":"设备到期预警.html",
  "generationDate":new Date(1476581093191.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ed6f07a5226845ffac7fd756e87000d2",
    "type":"Axure:Page",
    "name":"设备到期预警",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a231b2ff8ce94b868f46f820487ac69b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":15},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 煤炭洗选中心电气维修部",
                      "target":{
                        "targetType":"page",
                        "url":"煤炭洗选中心电气维修部.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8f68a70648f34e5b8bbd868216b7427b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":110},
            "size":{
              "width":570,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d4fbbf5a6e419aaf6230ca14499f35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3795aa87219243859327ef405e5f8ec1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u2.png"}},
{
              "id":"40144e49d3ff4458be10b0bf503575f9",
              "label":"z1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a1f03b1a0dc484caa64f57676c0edc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u2.png"}},
{
              "id":"b99c133db7a3493ba55c3c962b2d2c1f",
              "label":"x1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c51eb6505f3347119bc790d1db6ae167",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/x1_u14.png"}},
{
              "id":"18b9f4c03a484896bcbeb122b959b19a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4cf740d82ae4c2da131a8d64e57fdfc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u2.png"}},
{
              "id":"58e6835f6bf141f2a2230f816655414a",
              "label":"z2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5382cf095ac743d58a924d84c50f6665",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u2.png"}},
{
              "id":"389b307adce34dc59a8dfe67c939f3bd",
              "label":"x2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"86d0878b8010467397fb5a11c3bd7fe1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/x1_u14.png"}},
{
              "id":"c682df137cb746f387e1c40516ddb7b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bda28e2867c54438843e64985cd0a3cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u6.png"}},
{
              "id":"8fae3699bb41430da43c139ac785ffa6",
              "label":"z3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00ccb347bf67483dbbc7c40e0084cd6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/u6.png"}},
{
              "id":"34163816285a414099ace88152e9547d",
              "label":"x3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":60},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f15fabe15c6a4a18b275f40592f6ea5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备到期预警/x3_u18.png"}}]},
{
          "id":"8402e2eb4b0c4edcac7cd603ed412944",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":42},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3aef3b9e81a403a89773f5ebd2b8fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":244,
                  "y":42},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a54b48cf1fb499c8f751444a4cce93e",
          "label":"ok",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":48},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"957a710569b24f7c918fe67a5777daf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":651,
              "y":51},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dba99c8d3494600a2b40a68fbde1eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":651,
                  "y":51},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4b4200382b246ac89ee433bb1a1f1db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":766,
              "y":48},
            "size":{
              "width":17,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd909d5995374bf2bd062826c9274466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":766,
                  "y":48},
                "size":{
                  "width":17,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2681e917bcf44007b8c733b8b180f40b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":48},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 ok &lt; &quot;30&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["9a54b48cf1fb499c8f751444a4cce93e"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"30",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 z1 = &quot;001&quot;, 与<br> 文字于 z2 = &quot;6000V及以上电机&quot;, 与<br> 文字于 z3 = &quot;2016-11-01&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2a1f03b1a0dc484caa64f57676c0edc4"]},
{
                                "exprType":"stringLiteral",
                                "value":"001",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5382cf095ac743d58a924d84c50f6665"]},
{
                                "exprType":"stringLiteral",
                                "value":"6000V及以上电机",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["00ccb347bf67483dbbc7c40e0084cd6d"]},
{
                                "exprType":"stringLiteral",
                                "value":"2016-11-01",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true},
{
          "id":"ecf1180a991e41b3a2aa11c6e89cc204",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":216},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f794f21aa77443d8983ae405a923829d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":216},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a231b2ff8ce94b868f46f820487ac69b":{
      "scriptId":"u0"},
    "8f68a70648f34e5b8bbd868216b7427b":{
      "scriptId":"u1"},
    "36d4fbbf5a6e419aaf6230ca14499f35":{
      "scriptId":"u2"},
    "3795aa87219243859327ef405e5f8ec1":{
      "scriptId":"u3"},
    "18b9f4c03a484896bcbeb122b959b19a":{
      "scriptId":"u4"},
    "e4cf740d82ae4c2da131a8d64e57fdfc":{
      "scriptId":"u5"},
    "c682df137cb746f387e1c40516ddb7b9":{
      "scriptId":"u6"},
    "bda28e2867c54438843e64985cd0a3cd":{
      "scriptId":"u7"},
    "40144e49d3ff4458be10b0bf503575f9":{
      "scriptId":"u8"},
    "2a1f03b1a0dc484caa64f57676c0edc4":{
      "scriptId":"u9"},
    "58e6835f6bf141f2a2230f816655414a":{
      "scriptId":"u10"},
    "5382cf095ac743d58a924d84c50f6665":{
      "scriptId":"u11"},
    "8fae3699bb41430da43c139ac785ffa6":{
      "scriptId":"u12"},
    "00ccb347bf67483dbbc7c40e0084cd6d":{
      "scriptId":"u13"},
    "b99c133db7a3493ba55c3c962b2d2c1f":{
      "scriptId":"u14"},
    "c51eb6505f3347119bc790d1db6ae167":{
      "scriptId":"u15"},
    "389b307adce34dc59a8dfe67c939f3bd":{
      "scriptId":"u16"},
    "86d0878b8010467397fb5a11c3bd7fe1":{
      "scriptId":"u17"},
    "34163816285a414099ace88152e9547d":{
      "scriptId":"u18"},
    "f15fabe15c6a4a18b275f40592f6ea5b":{
      "scriptId":"u19"},
    "8402e2eb4b0c4edcac7cd603ed412944":{
      "scriptId":"u20"},
    "d3aef3b9e81a403a89773f5ebd2b8fa7":{
      "scriptId":"u21"},
    "9a54b48cf1fb499c8f751444a4cce93e":{
      "scriptId":"u22"},
    "957a710569b24f7c918fe67a5777daf2":{
      "scriptId":"u23"},
    "0dba99c8d3494600a2b40a68fbde1eb4":{
      "scriptId":"u24"},
    "e4b4200382b246ac89ee433bb1a1f1db":{
      "scriptId":"u25"},
    "bd909d5995374bf2bd062826c9274466":{
      "scriptId":"u26"},
    "2681e917bcf44007b8c733b8b180f40b":{
      "scriptId":"u27"},
    "ecf1180a991e41b3a2aa11c6e89cc204":{
      "scriptId":"u28"},
    "f794f21aa77443d8983ae405a923829d":{
      "scriptId":"u29"}}});