$axure.loadCurrentPage({
  "url":"煤炭洗选中心电气维修部.html",
  "generationDate":new Date(1476581086402.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69276088971649719619965bdbc9f73b",
    "type":"Axure:Page",
    "name":"煤炭洗选中心电气维修部",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2c04b67e5fc5469d94cbe1b67a985700",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":120},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备巡检录入",
                      "target":{
                        "targetType":"page",
                        "url":"设备巡检录入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bed58504946243d8ab8719ff11ff9c63",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":180,
              "y":40},
            "size":{
              "width":380,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"7e8bd76ad29d4223b65859b88aef4626",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":190},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备保养情况查询",
                      "target":{
                        "targetType":"page",
                        "url":"设备保养情况查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"decf66128d9143f3991a901a2e6d82f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":265},
            "size":{
              "width":310,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备到期预警",
                      "target":{
                        "targetType":"page",
                        "url":"设备到期预警.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "2c04b67e5fc5469d94cbe1b67a985700":{
      "scriptId":"u0"},
    "bed58504946243d8ab8719ff11ff9c63":{
      "scriptId":"u1"},
    "7e8bd76ad29d4223b65859b88aef4626":{
      "scriptId":"u2"},
    "decf66128d9143f3991a901a2e6d82f3":{
      "scriptId":"u3"}}});