$axure.loadCurrentPage({
  "url":"003.html",
  "generationDate":new Date(1476581092927.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e6df1a68957f44eea97926749421a9a2",
    "type":"Axure:Page",
    "name":"003",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"26a4ba325aec4bb8aa9c2c97ebbf52db",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":60},
            "size":{
              "width":548,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b35175b5db944c8485b0a480a30b74d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bae4ddf56bda456f93c2f13f743f8c38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"c6b7b6b5616644e482b400aee415deef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":294,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d932926668742d685c0c9677061c587",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u11.png"}},
{
              "id":"7159900c62c14eb78b92878cc030ee6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":294,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"792b0fa325cb45cdb16ad4e679c7f6f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":294,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u3.png"}},
{
              "id":"2ba02496ff6d47fca2f3f2e1794c3bc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":254,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d1b64bd270d74a6e9ddf3c6e59220e0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":254,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u5.png"}},
{
              "id":"22c41a5f8abe41d2a3f35821c261d6f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":36},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e06f3db47964ec4b165ad70561e6d56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":36},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"c4bbc5d0fcce4857b3e0525858b4c382",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":66},
                "size":{
                  "width":254,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50da5afc24b144fda3a374004e952fcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":66},
                    "size":{
                      "width":254,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u13.png"}},
{
              "id":"207e80f0ea93465b8340bc7fc50ad0c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"509fd55fabee41b2a95b574e7551a191",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"e2d5631d312f4dbd877e8faf19ca5dc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":92},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"537a41ddc9e942ffa0e49770b20f1ec8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":92},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"99896490fd3d42cbaeb47f41a8aaa6ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1af514ad8f5849ceb624581ec9779f96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u7.png"}},
{
              "id":"55c32d5ac2894427b79e8f42f52e9ad8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":122},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a88654af62bc45bab879d33a2cc62a16",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":122},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u9.png"}},
{
              "id":"9b6f7df285f048b3b593fdbe9321d676",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":152},
                "size":{
                  "width":294,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bccae674d9ba40af915fe8c59070f7b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":152},
                    "size":{
                      "width":294,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u23.png"}},
{
              "id":"57f92db259fb40d89868b988792d81da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":152},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2aeaef2570f6480898000cb71eed3dfa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":152},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u25.png"}}]},
{
          "id":"3bc30354f163479d80b55516d4534774",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":201.5,
              "y":260},
            "size":{
              "width":629,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b732113c3e4120a95e82eea73c3d07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":0},
                "size":{
                  "width":334,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0970319f8f2d4b6dbb4abee2a313a7b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":0},
                    "size":{
                      "width":334,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u30.png"}},
{
              "id":"d3de273092eb4766ba6fa865432367f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":36},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b59b12e3ca774c4eba6b0b9b7c467995",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":36},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"355fdf98721f41a9ad931d073dd317eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15c5221aed734b5b92803607e6f73724",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u32.png"}},
{
              "id":"a81ccc9ae0064d77b7a31435a40487a7",
              "label":"q1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":36},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b85fb69c4ec41aa9d3e9909f20bc637",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":36},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"1e902451ba314211abecceab20a0bd9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":187,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"710f188d4354418987d18a60046f394d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":187,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u34.png"}},
{
              "id":"23d586c24d9f4036b2a146914d18fceb",
              "label":"w1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":36},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"476882ed674c442aa570393466fc0f96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":36},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"66fd739e1fa44013ac149bfa6c75ee3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":38,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bab2df7aaff4637b019f72a799c6a45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":38,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u28.png"}},
{
              "id":"ada7d28b859744208f34044ea73d4886",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"799ee1a707374d4695cb8212b8773f55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"e796254124e84d59bf37d2a0c53f6649",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":38,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"881c2cac21384ba78825898f81c78740",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":38,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u44.png"}},
{
              "id":"75f8878221534e2597d22b9771e300e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":77},
                "size":{
                  "width":334,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b9f56c11604d58a9adf79d9a9f50b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":77},
                    "size":{
                      "width":334,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u46.png"}},
{
              "id":"09272527acfc4fc68688b2e2e4a3c616",
              "label":"q2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":77},
                "size":{
                  "width":70,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52a4ddf6d2694f7b85f0ea9d40406a0e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":77},
                    "size":{
                      "width":70,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q2_u48.png"}},
{
              "id":"ffb69086da45490bbf96f220fc4905b1",
              "label":"w2",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":77},
                "size":{
                  "width":187,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7872ddfcead42cf8d19a66ef76781ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":77},
                    "size":{
                      "width":187,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w2_u50.png"}},
{
              "id":"c97d944a85bf4f4195b7e840305ec711",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cb8d98639104f2699dd0c8ea1d29fb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":122},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"a235074bfe6d4a4395392d50b9cb145f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":122},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b3c9145eee4406a0d509e05c66872a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":122},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"53a85baaa1944afd84a0c3e9e3cb0fce",
              "label":"q3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":122},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02e9d35da38d4bbcb935393daec0b30d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":122},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"c6f5a6f1b561419ebc6d690df143790f",
              "label":"w3",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":122},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a3366556e1c4134b1984c614b0c6dd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":122},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"76222d51b8e843c8ab3cf25c1d1a347e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":161},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78ce98e2c8764260a6d6c9deb32b4fbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":161},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"7569ab244e25462cb1e03681a2808450",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":161},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"377619274bea4a1893bc5edc9c88fa21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":161},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"583ce0097cf04c0890e91667d1b2a80a",
              "label":"q4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":161},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5a06a6fefac41c29794df96f33f6077",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":161},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"4db8ca3297e34293a4c6ef672b772ec7",
              "label":"w4",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":161},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c73240563a2b494da3f9b773ae84d668",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":161},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"da1ef2787d3c44529b11328a109cd23b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":201},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"395b701dbe78452fbf1c45a87679f98e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":201},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"0277e9d5009846179180ed72734b527c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":201},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4abe97b4c42e4ee098898c351fec92f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":201},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"b40015ef21fe41beb48f456cef22fc9a",
              "label":"q5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":201},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d713e6be7c940c39c73c3999f6db426",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":201},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"59bb766f89e34dfe84392efd9708aa99",
              "label":"w5",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":201},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce3584d813ed4cda881786c4606179ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":201},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"a8da735461824b309829467ad085afe7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":242},
                "size":{
                  "width":38,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1abadb673465442ea84f6888d3951ac7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":38,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u36.png"}},
{
              "id":"22eebd89a2c84b969b0669f6544c47f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":242},
                "size":{
                  "width":334,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af4e5eb34ed24f6188038e7ee094e0db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":242},
                    "size":{
                      "width":334,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u38.png"}},
{
              "id":"ee0d6dcf03aa439e82d55d5935495ad5",
              "label":"q6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":242},
                "size":{
                  "width":70,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3383b61016464e1d96ea0c87e481c8a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":242},
                    "size":{
                      "width":70,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q1_u40.png"}},
{
              "id":"bd6b90a0b32b4139afc98f569e83a9b2",
              "label":"w6",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":242},
                "size":{
                  "width":187,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6bec52f875046659812dcba217aa5f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":242},
                    "size":{
                      "width":187,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w1_u42.png"}},
{
              "id":"ece5ed51b6d241788d0005f937781407",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":283},
                "size":{
                  "width":38,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e65cfc2c0f34d339b37f9aad49b91f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":38,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u60.png"}},
{
              "id":"ffe57531a3dc421a82739ac4ea3b0fb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":283},
                "size":{
                  "width":334,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d9f4ab8dd3d47df87ab7c08a8d52298",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":283},
                    "size":{
                      "width":334,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u62.png"}},
{
              "id":"b172399cda90409bb3b82f42ce799876",
              "label":"q7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":283},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac259eecc90445c4bcdf9948277d304d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":283},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q4_u64.png"}},
{
              "id":"635db43ef1b9493596b81420fa2595b2",
              "label":"w7",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":283},
                "size":{
                  "width":187,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"928ecde0de0a4e3ba7c388e5b61785b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":283},
                    "size":{
                      "width":187,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w4_u66.png"}},
{
              "id":"1375bccbdbc84fab8643f48b4efcbcb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":323},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b30ff484f424b2c9686d1b08797dfa3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":323},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"b01d9d3e06e2407fbefb72fc5ae61208",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":323},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2077bb06fb0642a6bbaf31d0354c29c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":323},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"5989295007dd486ca29eb563b7575051",
              "label":"q8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":323},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c75a559a80949d39190676c267db7a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":323},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"1d7c87ca69e64a9b952515777db03304",
              "label":"w8",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":323},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0a33d01a13640e89a62bd24c8202011",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":323},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"6459aefa3af2450ba0f966ac2d18d2b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":366},
                "size":{
                  "width":38,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d967c8c0b7f44870b09e727eb93595f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":366},
                    "size":{
                      "width":38,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u52.png"}},
{
              "id":"4c9510f13dd24bdf9737f631e01c7863",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":366},
                "size":{
                  "width":334,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f82e4df4f934a0792366b47b7b67b53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":366},
                    "size":{
                      "width":334,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u54.png"}},
{
              "id":"fffad453551a4e5688f0c6ee722ec5cd",
              "label":"q9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":366},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55ba80987e4143f7a8bcd045cd46fbb4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":366},
                    "size":{
                      "width":70,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q3_u56.png"}},
{
              "id":"4bc7c62c491b41e1b6bbd0c28692777a",
              "label":"w9",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":366},
                "size":{
                  "width":187,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79f6d41052cd4216b8480381773d3bbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":366},
                    "size":{
                      "width":187,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w3_u58.png"}},
{
              "id":"60102ea03ed74cb4b58e99297d5d9ca4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":405},
                "size":{
                  "width":38,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95c79fd60be04398b95a18b24a7152b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":405},
                    "size":{
                      "width":38,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u92.png"}},
{
              "id":"a2c61f7e4e314e9993196aab3f04004b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":405},
                "size":{
                  "width":334,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"daa3dd45810141d9894b123e83908fcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":405},
                    "size":{
                      "width":334,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u94.png"}},
{
              "id":"5ea1f101d7534282a82a583c11040bbd",
              "label":"q10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":405},
                "size":{
                  "width":70,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4254c670bfc94d3380e901777794ceff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":405},
                    "size":{
                      "width":70,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q8_u96.png"}},
{
              "id":"11e5f05696f649768d7025b1b61b1e44",
              "label":"w10",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":405},
                "size":{
                  "width":187,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06dfe69745124485ac5a70cb5736d711",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":405},
                    "size":{
                      "width":187,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/w8_u98.png"}},
{
              "id":"07ee107a845f4ce3ae5dd92788a157e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":448},
                "size":{
                  "width":38,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36466cee1b5849e1b7ddde33638b3794",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":448},
                    "size":{
                      "width":38,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u116.png"}},
{
              "id":"2402ee0a842943c8b110cae7551c3a62",
              "label":"q11",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":38,
                  "y":448},
                "size":{
                  "width":334,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45fa23bb41984f9a869fc5d5b861a22f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":38,
                      "y":448},
                    "size":{
                      "width":334,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/q11_u118.png"}},
{
              "id":"3fad9fbf78fa4cf1a0f74ed7e2d6ec00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":448},
                "size":{
                  "width":70,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39b6a45d99eb4d11b552faaca2b252e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":448},
                    "size":{
                      "width":70,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u120.png"}},
{
              "id":"aea3c542b85445e1bc36c5595fc85c44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":448},
                "size":{
                  "width":187,
                  "height":116}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8c35a1829dc4fd4b845a8d1ff0b26a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":448},
                    "size":{
                      "width":187,
                      "height":116}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备巡检录入/u122.png"}}]},
{
          "id":"ece7036941af468f83b4f42c4bb9e180",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":25},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 煤炭洗选中心电气维修部",
                      "target":{
                        "targetType":"page",
                        "url":"煤炭洗选中心电气维修部.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"41759aa8d95e4670a7276d7fc0bb477c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":860},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备保养情况查询",
                      "target":{
                        "targetType":"page",
                        "url":"设备保养情况查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "26a4ba325aec4bb8aa9c2c97ebbf52db":{
      "scriptId":"u0"},
    "7159900c62c14eb78b92878cc030ee6f":{
      "scriptId":"u1"},
    "792b0fa325cb45cdb16ad4e679c7f6f3":{
      "scriptId":"u2"},
    "2ba02496ff6d47fca2f3f2e1794c3bc3":{
      "scriptId":"u3"},
    "d1b64bd270d74a6e9ddf3c6e59220e0f":{
      "scriptId":"u4"},
    "b35175b5db944c8485b0a480a30b74d5":{
      "scriptId":"u5"},
    "bae4ddf56bda456f93c2f13f743f8c38":{
      "scriptId":"u6"},
    "22c41a5f8abe41d2a3f35821c261d6f5":{
      "scriptId":"u7"},
    "1e06f3db47964ec4b165ad70561e6d56":{
      "scriptId":"u8"},
    "c6b7b6b5616644e482b400aee415deef":{
      "scriptId":"u9"},
    "2d932926668742d685c0c9677061c587":{
      "scriptId":"u10"},
    "c4bbc5d0fcce4857b3e0525858b4c382":{
      "scriptId":"u11"},
    "50da5afc24b144fda3a374004e952fcb":{
      "scriptId":"u12"},
    "207e80f0ea93465b8340bc7fc50ad0c9":{
      "scriptId":"u13"},
    "509fd55fabee41b2a95b574e7551a191":{
      "scriptId":"u14"},
    "e2d5631d312f4dbd877e8faf19ca5dc5":{
      "scriptId":"u15"},
    "537a41ddc9e942ffa0e49770b20f1ec8":{
      "scriptId":"u16"},
    "99896490fd3d42cbaeb47f41a8aaa6ac":{
      "scriptId":"u17"},
    "1af514ad8f5849ceb624581ec9779f96":{
      "scriptId":"u18"},
    "55c32d5ac2894427b79e8f42f52e9ad8":{
      "scriptId":"u19"},
    "a88654af62bc45bab879d33a2cc62a16":{
      "scriptId":"u20"},
    "9b6f7df285f048b3b593fdbe9321d676":{
      "scriptId":"u21"},
    "bccae674d9ba40af915fe8c59070f7b4":{
      "scriptId":"u22"},
    "57f92db259fb40d89868b988792d81da":{
      "scriptId":"u23"},
    "2aeaef2570f6480898000cb71eed3dfa":{
      "scriptId":"u24"},
    "3bc30354f163479d80b55516d4534774":{
      "scriptId":"u25"},
    "66fd739e1fa44013ac149bfa6c75ee3f":{
      "scriptId":"u26"},
    "1bab2df7aaff4637b019f72a799c6a45":{
      "scriptId":"u27"},
    "d3b732113c3e4120a95e82eea73c3d07":{
      "scriptId":"u28"},
    "0970319f8f2d4b6dbb4abee2a313a7b2":{
      "scriptId":"u29"},
    "355fdf98721f41a9ad931d073dd317eb":{
      "scriptId":"u30"},
    "15c5221aed734b5b92803607e6f73724":{
      "scriptId":"u31"},
    "1e902451ba314211abecceab20a0bd9b":{
      "scriptId":"u32"},
    "710f188d4354418987d18a60046f394d":{
      "scriptId":"u33"},
    "ada7d28b859744208f34044ea73d4886":{
      "scriptId":"u34"},
    "799ee1a707374d4695cb8212b8773f55":{
      "scriptId":"u35"},
    "d3de273092eb4766ba6fa865432367f1":{
      "scriptId":"u36"},
    "b59b12e3ca774c4eba6b0b9b7c467995":{
      "scriptId":"u37"},
    "a81ccc9ae0064d77b7a31435a40487a7":{
      "scriptId":"u38"},
    "7b85fb69c4ec41aa9d3e9909f20bc637":{
      "scriptId":"u39"},
    "23d586c24d9f4036b2a146914d18fceb":{
      "scriptId":"u40"},
    "476882ed674c442aa570393466fc0f96":{
      "scriptId":"u41"},
    "e796254124e84d59bf37d2a0c53f6649":{
      "scriptId":"u42"},
    "881c2cac21384ba78825898f81c78740":{
      "scriptId":"u43"},
    "75f8878221534e2597d22b9771e300e7":{
      "scriptId":"u44"},
    "21b9f56c11604d58a9adf79d9a9f50b3":{
      "scriptId":"u45"},
    "09272527acfc4fc68688b2e2e4a3c616":{
      "scriptId":"u46"},
    "52a4ddf6d2694f7b85f0ea9d40406a0e":{
      "scriptId":"u47"},
    "ffb69086da45490bbf96f220fc4905b1":{
      "scriptId":"u48"},
    "a7872ddfcead42cf8d19a66ef76781ef":{
      "scriptId":"u49"},
    "c97d944a85bf4f4195b7e840305ec711":{
      "scriptId":"u50"},
    "8cb8d98639104f2699dd0c8ea1d29fb6":{
      "scriptId":"u51"},
    "a235074bfe6d4a4395392d50b9cb145f":{
      "scriptId":"u52"},
    "21b3c9145eee4406a0d509e05c66872a":{
      "scriptId":"u53"},
    "53a85baaa1944afd84a0c3e9e3cb0fce":{
      "scriptId":"u54"},
    "02e9d35da38d4bbcb935393daec0b30d":{
      "scriptId":"u55"},
    "c6f5a6f1b561419ebc6d690df143790f":{
      "scriptId":"u56"},
    "7a3366556e1c4134b1984c614b0c6dd1":{
      "scriptId":"u57"},
    "76222d51b8e843c8ab3cf25c1d1a347e":{
      "scriptId":"u58"},
    "78ce98e2c8764260a6d6c9deb32b4fbb":{
      "scriptId":"u59"},
    "7569ab244e25462cb1e03681a2808450":{
      "scriptId":"u60"},
    "377619274bea4a1893bc5edc9c88fa21":{
      "scriptId":"u61"},
    "583ce0097cf04c0890e91667d1b2a80a":{
      "scriptId":"u62"},
    "a5a06a6fefac41c29794df96f33f6077":{
      "scriptId":"u63"},
    "4db8ca3297e34293a4c6ef672b772ec7":{
      "scriptId":"u64"},
    "c73240563a2b494da3f9b773ae84d668":{
      "scriptId":"u65"},
    "da1ef2787d3c44529b11328a109cd23b":{
      "scriptId":"u66"},
    "395b701dbe78452fbf1c45a87679f98e":{
      "scriptId":"u67"},
    "0277e9d5009846179180ed72734b527c":{
      "scriptId":"u68"},
    "4abe97b4c42e4ee098898c351fec92f5":{
      "scriptId":"u69"},
    "b40015ef21fe41beb48f456cef22fc9a":{
      "scriptId":"u70"},
    "1d713e6be7c940c39c73c3999f6db426":{
      "scriptId":"u71"},
    "59bb766f89e34dfe84392efd9708aa99":{
      "scriptId":"u72"},
    "ce3584d813ed4cda881786c4606179ce":{
      "scriptId":"u73"},
    "a8da735461824b309829467ad085afe7":{
      "scriptId":"u74"},
    "1abadb673465442ea84f6888d3951ac7":{
      "scriptId":"u75"},
    "22eebd89a2c84b969b0669f6544c47f2":{
      "scriptId":"u76"},
    "af4e5eb34ed24f6188038e7ee094e0db":{
      "scriptId":"u77"},
    "ee0d6dcf03aa439e82d55d5935495ad5":{
      "scriptId":"u78"},
    "3383b61016464e1d96ea0c87e481c8a3":{
      "scriptId":"u79"},
    "bd6b90a0b32b4139afc98f569e83a9b2":{
      "scriptId":"u80"},
    "e6bec52f875046659812dcba217aa5f5":{
      "scriptId":"u81"},
    "ece5ed51b6d241788d0005f937781407":{
      "scriptId":"u82"},
    "1e65cfc2c0f34d339b37f9aad49b91f6":{
      "scriptId":"u83"},
    "ffe57531a3dc421a82739ac4ea3b0fb7":{
      "scriptId":"u84"},
    "7d9f4ab8dd3d47df87ab7c08a8d52298":{
      "scriptId":"u85"},
    "b172399cda90409bb3b82f42ce799876":{
      "scriptId":"u86"},
    "ac259eecc90445c4bcdf9948277d304d":{
      "scriptId":"u87"},
    "635db43ef1b9493596b81420fa2595b2":{
      "scriptId":"u88"},
    "928ecde0de0a4e3ba7c388e5b61785b5":{
      "scriptId":"u89"},
    "1375bccbdbc84fab8643f48b4efcbcb7":{
      "scriptId":"u90"},
    "9b30ff484f424b2c9686d1b08797dfa3":{
      "scriptId":"u91"},
    "b01d9d3e06e2407fbefb72fc5ae61208":{
      "scriptId":"u92"},
    "2077bb06fb0642a6bbaf31d0354c29c0":{
      "scriptId":"u93"},
    "5989295007dd486ca29eb563b7575051":{
      "scriptId":"u94"},
    "1c75a559a80949d39190676c267db7a1":{
      "scriptId":"u95"},
    "1d7c87ca69e64a9b952515777db03304":{
      "scriptId":"u96"},
    "f0a33d01a13640e89a62bd24c8202011":{
      "scriptId":"u97"},
    "6459aefa3af2450ba0f966ac2d18d2b1":{
      "scriptId":"u98"},
    "d967c8c0b7f44870b09e727eb93595f7":{
      "scriptId":"u99"},
    "4c9510f13dd24bdf9737f631e01c7863":{
      "scriptId":"u100"},
    "7f82e4df4f934a0792366b47b7b67b53":{
      "scriptId":"u101"},
    "fffad453551a4e5688f0c6ee722ec5cd":{
      "scriptId":"u102"},
    "55ba80987e4143f7a8bcd045cd46fbb4":{
      "scriptId":"u103"},
    "4bc7c62c491b41e1b6bbd0c28692777a":{
      "scriptId":"u104"},
    "79f6d41052cd4216b8480381773d3bbc":{
      "scriptId":"u105"},
    "60102ea03ed74cb4b58e99297d5d9ca4":{
      "scriptId":"u106"},
    "95c79fd60be04398b95a18b24a7152b7":{
      "scriptId":"u107"},
    "a2c61f7e4e314e9993196aab3f04004b":{
      "scriptId":"u108"},
    "daa3dd45810141d9894b123e83908fcf":{
      "scriptId":"u109"},
    "5ea1f101d7534282a82a583c11040bbd":{
      "scriptId":"u110"},
    "4254c670bfc94d3380e901777794ceff":{
      "scriptId":"u111"},
    "11e5f05696f649768d7025b1b61b1e44":{
      "scriptId":"u112"},
    "06dfe69745124485ac5a70cb5736d711":{
      "scriptId":"u113"},
    "07ee107a845f4ce3ae5dd92788a157e1":{
      "scriptId":"u114"},
    "36466cee1b5849e1b7ddde33638b3794":{
      "scriptId":"u115"},
    "2402ee0a842943c8b110cae7551c3a62":{
      "scriptId":"u116"},
    "45fa23bb41984f9a869fc5d5b861a22f":{
      "scriptId":"u117"},
    "3fad9fbf78fa4cf1a0f74ed7e2d6ec00":{
      "scriptId":"u118"},
    "39b6a45d99eb4d11b552faaca2b252e5":{
      "scriptId":"u119"},
    "aea3c542b85445e1bc36c5595fc85c44":{
      "scriptId":"u120"},
    "d8c35a1829dc4fd4b845a8d1ff0b26a8":{
      "scriptId":"u121"},
    "ece7036941af468f83b4f42c4bb9e180":{
      "scriptId":"u122"},
    "41759aa8d95e4670a7276d7fc0bb477c":{
      "scriptId":"u123"}}});